# Documentation for yarn nodeLinker option
# https://yarnpkg.com/configuration/yarnrc#node:Linker
nodeLinker: "node-modules"

# yarnPath option has been disabled (compared to other Altinn repos)
# because the documentation claims Corepack is best practice:
# https://yarnpkg.com/configuration/yarnrc#yarnPath
# yarnPath: .yarn/releases/yarn-3.6.3.cjs
