//Change to the correct rootUrl for testing locally or towards servers
//Within VS debugger
//@rootUrl = https://localhost:44349
@rootHttpsUrl = https://localhost:7170
@rootHttpUrl = http://localhost:5006
@authApiRootUrl = http://localhost:5101
@localAltinCloud = http://local.altinn.cloud

###
//The Homecontroller returns the index.html which launches the React SPA
//Expected result: React SPA index.html with minified js bundle
//Requires either a valid cookie with XSRF Token in the header
//or the Developer/Tester must switch off the Authorize attribute in the Controller.
GET {{rootHttpsUrl}}/authfront/ui/

###
//The endpoint for retrieving the name and info of the logged in user
//Expected result: a DTO with only username and organizationname
//Should either be already logged in via DialogPorten, mock a test Cookie 
//or switch off the Authorize attribute in the Controller.
{
  "userName": "Testur Testursson",
  "organizationName": "TestParty"
}

GET {{rootHttpUrl}}/authfront/api/v1/profile/user

###
//The endpoint for refreshing a Token
//Expected result: a new Token
//Needs a valid cookie with XSRF Token in the header to work,
//or the Developer/Tester must switch off the Authorize attribute in the Controller.
GET {{rootHttpUrl}}/authfront/api/v1/authentication/refresh


###
//GET {{AuthApiRootUrl}}/authentication/api/v1/authentication

###
GET {{rootHttpUrl}}/authfront/ui/auth/overview