//Change to the correct rootUrl for testing locally or towards servers
//Within VS debugger
@rootUrl = https://localhost:44349

###
//The Homecontroller returns the index.html which launches the React SPA
//Expected result: React SPA index.html with minified js bundle
GET {{rootUrl}}/authfront/ui/

###
//The endpoint for retrieving the name and info of the logged in user
//Expected result: a DTO with only username and organizationname
//Should either be already logged in via DialogPorten, or mock a test Cookie 
{
  "userName": "Testur Testursson",
  "organizationName": "TestParty"
}

GET {{rootUrl}}/authfront/api/v1/profile/user

###
//The endpoint for refreshing a Token
//Expected result: a new Token
GET {{rootUrl}}/authfront/api/v1/authentication/refresh


