name: Manually build and publish to a specific environments
on:
  workflow_dispatch:
    inputs:
        environment:
          type: environment
          description: Select the environment

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/altinn/altinn-authentication-frontend:${{ github.sha }}
          build-args: |
            SOURCE_REVISION_ID=${{ github.sha }}

  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs:
      - build

    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: ./.github/actions/deploy
        name: Deploy
        with:
          image-tag: ${{ github.sha }}
          resource-group: ${{ vars.CONTAINER_APP_RESOURCE_GROUP_NAME }}
          container-app: ${{ vars.CONTAINER_APP_NAME }}