name: Scheduled Playwright Tests

on:
  schedule:
    # Runs at 7:00 AM UTC every day
    - cron: "0 7 * * *"
    # Runs at 1:00 PM UTC every day
    - cron: "0 13 * * *"

jobs:
  playwright-scheduled:
    name: "Scheduled Playwright tests"
    uses: ./.github/workflows/template-test-playwright.yml
    with:
      environment: ${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment: [AT22]
    secrets:
      USERNAME_TEST_API: ${{ secrets.USERNAME_TEST_API }}
      PASSWORD_TEST_API: ${{ secrets.PASSWORD_TEST_API }}
