name: Playwright tests (Authentication)


on:
  workflow_dispatch:  # Allows manual trigger only

jobs:
  playwright-scheduled:
    name: "Scheduled Playwright tests"
    uses: ./.github/workflows/template-test-playwright.yml
    with:
      environment: ${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment: [AT22, TT02]
    secrets:
      USERNAME_TEST_API: ${{ secrets.USERNAME_TEST_API }}
      PASSWORD_TEST_API: ${{ secrets.PASSWORD_TEST_API }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
