name: template-test-playwright.yml

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Environment

jobs:
  playwright:
    name: "Playwright end to end Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack to use yarn version > 1
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: frontend/playwright
        run: |
          yarn --immutable
          yarn playwright install --with-deps
      - name: Run Playwright tests
        working-directory: frontend/playwright
        run: yarn run env:${{ inputs.environment }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: frontend/playwright/test-results/${{ inputs.environment }}
          retention-days: 30
